import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { formatData, getLocalData } from "../lib/api";

export default function Home({ data }) {
  console.log(`data: `, data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main></main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const categories = await getLocalData(`categories`);
  const posts = await getLocalData(`posts`);
  // const formatedData = await formatData(); // 提取数据
  return {
    props: { data: { categories, posts } },
  };
}
